[package]
name = "wakulima-solana-escrow"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "1.10.7"
thiserror = "1.0.24"

[lib]
crate-type = ["cdylib", "lib"]